/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import controller.AddStaffController;
import java.awt.Color;
import javax.swing.JFrame;


/**
 *
 * @author amritchand
 */
public class AddEmployee extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AddEmployee.class.getName());

    /**
     * Creates new form AdminUi
     */
    public AddEmployee() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        // Make the "Add Employee" button blue when this window opens
        add_employee_btn1.setBackground(new Color(0, 125, 234)); 
        add_employee_btn1.setForeground(Color.WHITE);            
        add_employee_btn1.setOpaque(true);                    
        add_employee_btn1.setBorderPainted(false);   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        blue_panel = new javax.swing.JPanel();
        bms_text = new javax.swing.JLabel();
        logo_panel = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        horizon_text = new javax.swing.JLabel();
        pic_outside_panel = new javax.swing.JPanel();
        skyblue_panel = new javax.swing.JPanel();
        add_employee_btn1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        emp_name_txt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        emp_add_btn = new javax.swing.JButton();
        emp_pass_txt = new javax.swing.JTextField();
        emp_email_txt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        roleLabel = new javax.swing.JLabel();
        emp_role_txt = new javax.swing.JTextField();
        emp_number_txt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        emp_address_txt = new javax.swing.JTextField();
        back_btn = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        blue_panel.setBackground(new java.awt.Color(83, 12, 205));
        blue_panel.setPreferredSize(new java.awt.Dimension(100, 100));

        bms_text.setFont(new java.awt.Font("Helvetica Neue", 1, 48)); // NOI18N
        bms_text.setForeground(new java.awt.Color(255, 255, 255));
        bms_text.setText("Bank Management System");
        bms_text.setPreferredSize(new java.awt.Dimension(615, 60));

        logo_panel.setBackground(new java.awt.Color(83, 12, 205));

        logo.setBackground(new java.awt.Color(83, 12, 205));
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/resized_logo.png"))); // NOI18N
        logo.setPreferredSize(new java.awt.Dimension(75, 75));

        horizon_text.setForeground(new java.awt.Color(255, 255, 255));
        horizon_text.setText("HORIZON BANK");

        javax.swing.GroupLayout logo_panelLayout = new javax.swing.GroupLayout(logo_panel);
        logo_panel.setLayout(logo_panelLayout);
        logo_panelLayout.setHorizontalGroup(
            logo_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logo_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(horizon_text)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logo_panelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        logo_panelLayout.setVerticalGroup(
            logo_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logo_panelLayout.createSequentialGroup()
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(horizon_text)
                .addContainerGap())
        );

        javax.swing.GroupLayout blue_panelLayout = new javax.swing.GroupLayout(blue_panel);
        blue_panel.setLayout(blue_panelLayout);
        blue_panelLayout.setHorizontalGroup(
            blue_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, blue_panelLayout.createSequentialGroup()
                .addComponent(logo_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bms_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(462, 462, 462))
        );
        blue_panelLayout.setVerticalGroup(
            blue_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(blue_panelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(bms_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, blue_panelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logo_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81))
        );

        pic_outside_panel.setBackground(new java.awt.Color(147, 181, 211));
        pic_outside_panel.setPreferredSize(new java.awt.Dimension(311, 930));
        pic_outside_panel.setLayout(null);

        skyblue_panel.setBackground(new java.awt.Color(20, 120, 157));
        skyblue_panel.setPreferredSize(new java.awt.Dimension(291, 930));

        add_employee_btn1.setFont(new java.awt.Font("Helvetica Neue", 1, 12)); // NOI18N
        add_employee_btn1.setText("CREATE EMP ACCOUNT");
        add_employee_btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_employee_btn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout skyblue_panelLayout = new javax.swing.GroupLayout(skyblue_panel);
        skyblue_panel.setLayout(skyblue_panelLayout);
        skyblue_panelLayout.setHorizontalGroup(
            skyblue_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(skyblue_panelLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(add_employee_btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );
        skyblue_panelLayout.setVerticalGroup(
            skyblue_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(skyblue_panelLayout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addComponent(add_employee_btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1587, Short.MAX_VALUE))
        );

        pic_outside_panel.add(skyblue_panel);
        skyblue_panel.setBounds(0, 0, 290, 1800);

        jPanel1.setBackground(new java.awt.Color(222, 243, 247));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Add Employee");

        emp_name_txt.setBackground(new java.awt.Color(147, 181, 211));
        emp_name_txt.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        emp_name_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emp_name_txtActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Full Name");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Email");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Phone Number");

        emp_add_btn.setBackground(new java.awt.Color(0, 125, 234));
        emp_add_btn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        emp_add_btn.setForeground(new java.awt.Color(255, 255, 255));
        emp_add_btn.setText("ADD");
        emp_add_btn.setToolTipText("");
        emp_add_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emp_add_btnActionPerformed(evt);
            }
        });

        emp_pass_txt.setBackground(new java.awt.Color(147, 181, 211));
        emp_pass_txt.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        emp_pass_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emp_pass_txtActionPerformed(evt);
            }
        });

        emp_email_txt.setBackground(new java.awt.Color(147, 181, 211));
        emp_email_txt.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        emp_email_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emp_email_txtActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Password");

        roleLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        roleLabel.setText("User Role");

        emp_role_txt.setBackground(new java.awt.Color(147, 181, 211));
        emp_role_txt.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        emp_role_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emp_role_txtActionPerformed(evt);
            }
        });

        emp_number_txt.setBackground(new java.awt.Color(147, 181, 211));
        emp_number_txt.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        emp_number_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emp_number_txtActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("Address");

        emp_address_txt.setBackground(new java.awt.Color(147, 181, 211));
        emp_address_txt.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        emp_address_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emp_address_txtActionPerformed(evt);
            }
        });

        back_btn.setBackground(new java.awt.Color(179, 28, 221));
        back_btn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        back_btn.setForeground(new java.awt.Color(255, 255, 255));
        back_btn.setText("BACK");
        back_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(69, 69, 69)
                        .addComponent(emp_name_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(roleLabel))
                        .addGap(46, 46, 46)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(emp_role_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emp_number_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emp_pass_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emp_email_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emp_address_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(75, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(169, 169, 169))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(emp_add_btn, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                            .addComponent(back_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(129, 129, 129))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(emp_name_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emp_email_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(emp_pass_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emp_number_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emp_address_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emp_role_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(roleLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(emp_add_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(back_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        pic_outside_panel.add(jPanel1);
        jPanel1.setBounds(580, 60, 570, 700);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(blue_panel, javax.swing.GroupLayout.DEFAULT_SIZE, 1470, Short.MAX_VALUE)
            .addComponent(pic_outside_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(blue_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pic_outside_panel, javax.swing.GroupLayout.PREFERRED_SIZE, 820, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void emp_name_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emp_name_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emp_name_txtActionPerformed

    private void emp_add_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emp_add_btnActionPerformed
        // TODO add your handling code here:
        // 1. Get input values from text fields
        String fullName = emp_name_txt.getText();
        String email = emp_email_txt.getText();
        String password = emp_pass_txt.getText(); // for JPasswordField
        String phone = emp_number_txt.getText();
        String address = emp_address_txt.getText();
        String role = emp_role_txt.getText();
        
        // 2. Create controller instance
        AddStaffController controller = new AddStaffController();

        // 3. Call controller to add employee
        boolean success = controller.addEmployee(fullName, email, password, phone, address, role);
        
        if(success) {
            //Clear fields
            emp_name_txt.setText("");
            emp_email_txt.setText("");
            emp_pass_txt.setText("");
            emp_number_txt.setText("");
            emp_address_txt.setText("");
            emp_role_txt.setText("");
        }

        
    }//GEN-LAST:event_emp_add_btnActionPerformed

    private void emp_pass_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emp_pass_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emp_pass_txtActionPerformed

    private void emp_email_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emp_email_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emp_email_txtActionPerformed

    private void add_employee_btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_employee_btn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_add_employee_btn1ActionPerformed

    private void emp_role_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emp_role_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emp_role_txtActionPerformed

    private void emp_number_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emp_number_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emp_number_txtActionPerformed

    private void emp_address_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emp_address_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emp_address_txtActionPerformed

    private void back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_btnActionPerformed
        // TODO add your handling code here:
        AdminUi ad = new AdminUi();
        ad.setVisible(true);
        this.setVisible(false);       

    }//GEN-LAST:event_back_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AddEmployee().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_employee_btn1;
    private javax.swing.JToggleButton back_btn;
    private javax.swing.JPanel blue_panel;
    private javax.swing.JLabel bms_text;
    private javax.swing.JButton emp_add_btn;
    private javax.swing.JTextField emp_address_txt;
    private javax.swing.JTextField emp_email_txt;
    private javax.swing.JTextField emp_name_txt;
    private javax.swing.JTextField emp_number_txt;
    private javax.swing.JTextField emp_pass_txt;
    private javax.swing.JTextField emp_role_txt;
    private javax.swing.JLabel horizon_text;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel logo;
    private javax.swing.JPanel logo_panel;
    private javax.swing.JPanel pic_outside_panel;
    private javax.swing.JLabel roleLabel;
    private javax.swing.JPanel skyblue_panel;
    // End of variables declaration//GEN-END:variables
}
