/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import controller.AddCustomerController;
import java.awt.Color;

/**
 *
 * @author jenis
 */
public class CustomerAddUi extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CustomerAddUi.class.getName());

    /**
     * Creates new form AdminUi
     */
    public CustomerAddUi() {
        initComponents();
        account_number_txt.setEditable(false);
        customer_add_btn.setBackground(new Color(0, 125, 234)); 
        customer_add_btn.setForeground(Color.WHITE);            
        customer_add_btn.setOpaque(true);                    
        customer_add_btn.setBorderPainted(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        blue_panel = new javax.swing.JPanel();
        bms_text = new javax.swing.JLabel();
        logo_panel = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        horizon_text = new javax.swing.JLabel();
        pic_outside_panel = new javax.swing.JPanel();
        skyblue_panel = new javax.swing.JPanel();
        customer_add_btn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        full_name_txt = new javax.swing.JTextField();
        account_type = new javax.swing.JLabel();
        add_btn = new javax.swing.JButton();
        dob = new javax.swing.JLabel();
        id_proof_txt = new javax.swing.JTextField();
        email_txt = new javax.swing.JTextField();
        id_proof = new javax.swing.JLabel();
        dob_txt = new javax.swing.JTextField();
        phone_number = new javax.swing.JLabel();
        phone_number_txt = new javax.swing.JTextField();
        address = new javax.swing.JLabel();
        address_txt = new javax.swing.JTextField();
        full_name = new javax.swing.JLabel();
        account_number = new javax.swing.JLabel();
        account_number_txt = new javax.swing.JTextField();
        generate_btn = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        back_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        blue_panel.setBackground(new java.awt.Color(83, 12, 205));
        blue_panel.setPreferredSize(new java.awt.Dimension(100, 100));

        bms_text.setFont(new java.awt.Font("Helvetica Neue", 1, 48)); // NOI18N
        bms_text.setForeground(new java.awt.Color(255, 255, 255));
        bms_text.setText("Bank Management System");
        bms_text.setPreferredSize(new java.awt.Dimension(615, 60));

        logo_panel.setBackground(new java.awt.Color(83, 12, 205));

        logo.setBackground(new java.awt.Color(83, 12, 205));
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/resized_logo.png"))); // NOI18N
        logo.setPreferredSize(new java.awt.Dimension(75, 75));

        horizon_text.setForeground(new java.awt.Color(255, 255, 255));
        horizon_text.setText("HORIZON BANK");

        javax.swing.GroupLayout logo_panelLayout = new javax.swing.GroupLayout(logo_panel);
        logo_panel.setLayout(logo_panelLayout);
        logo_panelLayout.setHorizontalGroup(
            logo_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logo_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(horizon_text)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logo_panelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        logo_panelLayout.setVerticalGroup(
            logo_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logo_panelLayout.createSequentialGroup()
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(horizon_text)
                .addContainerGap())
        );

        javax.swing.GroupLayout blue_panelLayout = new javax.swing.GroupLayout(blue_panel);
        blue_panel.setLayout(blue_panelLayout);
        blue_panelLayout.setHorizontalGroup(
            blue_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, blue_panelLayout.createSequentialGroup()
                .addComponent(logo_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 284, Short.MAX_VALUE)
                .addComponent(bms_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(462, 462, 462))
        );
        blue_panelLayout.setVerticalGroup(
            blue_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(blue_panelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(bms_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, blue_panelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logo_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81))
        );

        pic_outside_panel.setBackground(new java.awt.Color(147, 181, 211));
        pic_outside_panel.setPreferredSize(new java.awt.Dimension(311, 930));
        pic_outside_panel.setLayout(null);

        skyblue_panel.setBackground(new java.awt.Color(20, 120, 157));
        skyblue_panel.setPreferredSize(new java.awt.Dimension(291, 930));

        customer_add_btn.setBackground(new java.awt.Color(217, 217, 217));
        customer_add_btn.setFont(new java.awt.Font("Helvetica Neue", 1, 12)); // NOI18N
        customer_add_btn.setText("CREATE CUST ACCOUNT");
        customer_add_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customer_add_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout skyblue_panelLayout = new javax.swing.GroupLayout(skyblue_panel);
        skyblue_panel.setLayout(skyblue_panelLayout);
        skyblue_panelLayout.setHorizontalGroup(
            skyblue_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(skyblue_panelLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(customer_add_btn)
                .addContainerGap(56, Short.MAX_VALUE))
        );
        skyblue_panelLayout.setVerticalGroup(
            skyblue_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(skyblue_panelLayout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addComponent(customer_add_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1588, Short.MAX_VALUE))
        );

        pic_outside_panel.add(skyblue_panel);
        skyblue_panel.setBounds(0, 0, 290, 1800);

        jPanel1.setBackground(new java.awt.Color(222, 243, 247));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 28)); // NOI18N
        jLabel1.setText("Create Customer Account");

        email.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        email.setText("Email");

        full_name_txt.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        full_name_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                full_name_txtActionPerformed(evt);
            }
        });

        account_type.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        account_type.setText("Account Type");

        add_btn.setBackground(new java.awt.Color(0, 125, 234));
        add_btn.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        add_btn.setForeground(new java.awt.Color(255, 255, 255));
        add_btn.setText("ADD");
        add_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_btnActionPerformed(evt);
            }
        });

        dob.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        dob.setText("Date of Birth");

        id_proof_txt.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        id_proof_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_proof_txtActionPerformed(evt);
            }
        });

        email_txt.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        email_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                email_txtActionPerformed(evt);
            }
        });

        id_proof.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        id_proof.setText("ID Proof Number");

        dob_txt.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        dob_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dob_txtActionPerformed(evt);
            }
        });

        phone_number.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        phone_number.setText("Phone Number");

        phone_number_txt.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        phone_number_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phone_number_txtActionPerformed(evt);
            }
        });

        address.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        address.setText("Address");

        address_txt.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        address_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                address_txtActionPerformed(evt);
            }
        });

        full_name.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        full_name.setText("Full Name");

        account_number.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        account_number.setText("Account Number");

        account_number_txt.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        account_number_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                account_number_txtActionPerformed(evt);
            }
        });

        generate_btn.setBackground(new java.awt.Color(25, 135, 84));
        generate_btn.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        generate_btn.setForeground(new java.awt.Color(255, 255, 255));
        generate_btn.setText("GENERATE");
        generate_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generate_btnActionPerformed(evt);
            }
        });

        jComboBox1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Saving", "Current", "Fixed Deposit" }));

        back_btn.setBackground(new java.awt.Color(179, 28, 221));
        back_btn.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        back_btn.setForeground(new java.awt.Color(255, 255, 255));
        back_btn.setText("BACK");
        back_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(267, 267, 267)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 49, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(id_proof, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(dob, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(phone_number, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE))
                        .addComponent(full_name, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(address, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(email, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(phone_number_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(id_proof_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(add_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(105, 105, 105))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(full_name_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(email_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dob_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(40, 40, 40)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(account_number, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(account_type, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(40, 40, 40)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(account_number_txt)
                                        .addComponent(generate_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(address_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(244, 244, 244)
                                .addComponent(back_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(94, 94, 94))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(full_name_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(account_type, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(full_name, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(account_number, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(generate_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(email_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dob_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dob, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 21, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(account_number_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(phone_number, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(phone_number_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(add_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(address, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(address_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(back_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(id_proof_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(id_proof, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64))
        );

        pic_outside_panel.add(jPanel1);
        jPanel1.setBounds(410, 120, 940, 590);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(blue_panel, javax.swing.GroupLayout.DEFAULT_SIZE, 1470, Short.MAX_VALUE)
            .addComponent(pic_outside_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(blue_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pic_outside_panel, javax.swing.GroupLayout.PREFERRED_SIZE, 820, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void customer_add_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customer_add_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customer_add_btnActionPerformed

    private void full_name_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_full_name_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_full_name_txtActionPerformed

    private void id_proof_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_proof_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id_proof_txtActionPerformed

    private void email_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_email_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_email_txtActionPerformed

    private void dob_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dob_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dob_txtActionPerformed

    private void phone_number_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phone_number_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phone_number_txtActionPerformed

    private void address_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_address_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_address_txtActionPerformed

    private void account_number_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_account_number_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_account_number_txtActionPerformed

    private void generate_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generate_btnActionPerformed
        // TODO add your handling code here:
        AddCustomerController generate1 = new AddCustomerController();
        String generatedAccNumber = generate1.generateAccountNumber();
        // Display in the account number text field
        account_number_txt.setText(generatedAccNumber);
        
    }//GEN-LAST:event_generate_btnActionPerformed

    private void add_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_btnActionPerformed
        // TODO add your handling code here:
        
        // Get all values from text fields
        String fullName1 = full_name_txt.getText();
        String email1 = email_txt.getText();
        String dob1 = dob_txt.getText();
        String phone1 = phone_number_txt.getText();
        String address1 = address_txt.getText();
        String idProof1 = id_proof_txt.getText();
        
        // Get account type from combo box
        String accountType1 = (String) jComboBox1.getSelectedItem();
        String accountNumber1 = account_number_txt.getText();
        
        AddCustomerController controller = new AddCustomerController();

        // Call controller to add customer
        boolean success = controller.addCustomer(fullName1, email1, dob1,
                phone1, address1, idProof1, accountType1, accountNumber1);

        if (success) {
            // Clear fields after successful addition
            full_name_txt.setText("");
            email_txt.setText("");
            dob_txt.setText("");
            phone_number_txt.setText("");
            address_txt.setText("");
            id_proof_txt.setText("");
            jComboBox1.setSelectedIndex(0); // Reset combo box to first item
            account_number_txt.setText("");
        }        
    }//GEN-LAST:event_add_btnActionPerformed

    private void back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_btnActionPerformed
        // TODO add your handling code here:
        EmployeeDashboard empDash = new EmployeeDashboard();
        empDash.setVisible(true);
        this.setVisible(false);          
    }//GEN-LAST:event_back_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CustomerAddUi().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel account_number;
    private javax.swing.JTextField account_number_txt;
    private javax.swing.JLabel account_type;
    private javax.swing.JButton add_btn;
    private javax.swing.JLabel address;
    private javax.swing.JTextField address_txt;
    private javax.swing.JButton back_btn;
    private javax.swing.JPanel blue_panel;
    private javax.swing.JLabel bms_text;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton customer_add_btn;
    private javax.swing.JLabel dob;
    private javax.swing.JTextField dob_txt;
    private javax.swing.JLabel email;
    private javax.swing.JTextField email_txt;
    private javax.swing.JLabel full_name;
    private javax.swing.JTextField full_name_txt;
    private javax.swing.JButton generate_btn;
    private javax.swing.JLabel horizon_text;
    private javax.swing.JLabel id_proof;
    private javax.swing.JTextField id_proof_txt;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel logo;
    private javax.swing.JPanel logo_panel;
    private javax.swing.JLabel phone_number;
    private javax.swing.JTextField phone_number_txt;
    private javax.swing.JPanel pic_outside_panel;
    private javax.swing.JPanel skyblue_panel;
    // End of variables declaration//GEN-END:variables
}
