/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import controller.NoticeController;
/**
 *
 * @author amritchand
 */
public class NoticUi extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(NoticUi.class.getName());

    /**
     * Creates new form AdminUi
     */
    public NoticUi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        blue_panel = new javax.swing.JPanel();
        bms_text = new javax.swing.JLabel();
        logo_panel = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        horizon_text = new javax.swing.JLabel();
        pic_outside_panel = new javax.swing.JPanel();
        skyblue_panel = new javax.swing.JPanel();
        dashboard_btn = new javax.swing.JButton();
        create_notice_btn = new javax.swing.JButton();
        history_btn = new javax.swing.JButton();
        add_employee_btn1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        notice_post_btn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        notice_txt = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        blue_panel.setBackground(new java.awt.Color(83, 12, 205));
        blue_panel.setPreferredSize(new java.awt.Dimension(100, 100));

        bms_text.setFont(new java.awt.Font("Helvetica Neue", 1, 48)); // NOI18N
        bms_text.setForeground(new java.awt.Color(255, 255, 255));
        bms_text.setText("Bank Management System");
        bms_text.setPreferredSize(new java.awt.Dimension(615, 60));

        logo_panel.setBackground(new java.awt.Color(83, 12, 205));

        logo.setBackground(new java.awt.Color(83, 12, 205));
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/resized_logo.png"))); // NOI18N
        logo.setPreferredSize(new java.awt.Dimension(75, 75));

        horizon_text.setForeground(new java.awt.Color(255, 255, 255));
        horizon_text.setText("HORIZON BANK");

        javax.swing.GroupLayout logo_panelLayout = new javax.swing.GroupLayout(logo_panel);
        logo_panel.setLayout(logo_panelLayout);
        logo_panelLayout.setHorizontalGroup(
            logo_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logo_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(horizon_text)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logo_panelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        logo_panelLayout.setVerticalGroup(
            logo_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logo_panelLayout.createSequentialGroup()
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(horizon_text)
                .addContainerGap())
        );

        javax.swing.GroupLayout blue_panelLayout = new javax.swing.GroupLayout(blue_panel);
        blue_panel.setLayout(blue_panelLayout);
        blue_panelLayout.setHorizontalGroup(
            blue_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, blue_panelLayout.createSequentialGroup()
                .addComponent(logo_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bms_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(462, 462, 462))
        );
        blue_panelLayout.setVerticalGroup(
            blue_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(blue_panelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(bms_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, blue_panelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logo_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81))
        );

        pic_outside_panel.setBackground(new java.awt.Color(147, 181, 211));
        pic_outside_panel.setPreferredSize(new java.awt.Dimension(311, 930));
        pic_outside_panel.setLayout(null);

        skyblue_panel.setBackground(new java.awt.Color(20, 120, 157));
        skyblue_panel.setPreferredSize(new java.awt.Dimension(291, 930));

        dashboard_btn.setFont(new java.awt.Font("Helvetica Neue", 1, 12)); // NOI18N
        dashboard_btn.setText("DASHBOARD");
        dashboard_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dashboard_btnActionPerformed(evt);
            }
        });

        create_notice_btn.setFont(new java.awt.Font("Helvetica Neue", 1, 12)); // NOI18N
        create_notice_btn.setText("CREATE NOTICE");
        create_notice_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                create_notice_btnActionPerformed(evt);
            }
        });

        history_btn.setFont(new java.awt.Font("Helvetica Neue", 1, 12)); // NOI18N
        history_btn.setText("TRANSACTION HISTORY");
        history_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                history_btnActionPerformed(evt);
            }
        });

        add_employee_btn1.setFont(new java.awt.Font("Helvetica Neue", 1, 12)); // NOI18N
        add_employee_btn1.setText("CREATE EMP ACCOUNT");
        add_employee_btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_employee_btn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout skyblue_panelLayout = new javax.swing.GroupLayout(skyblue_panel);
        skyblue_panel.setLayout(skyblue_panelLayout);
        skyblue_panelLayout.setHorizontalGroup(
            skyblue_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(skyblue_panelLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(skyblue_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(skyblue_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(history_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(dashboard_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(skyblue_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(create_notice_btn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(add_employee_btn1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        skyblue_panelLayout.setVerticalGroup(
            skyblue_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(skyblue_panelLayout.createSequentialGroup()
                .addGap(183, 183, 183)
                .addComponent(dashboard_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84)
                .addComponent(history_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84)
                .addComponent(add_employee_btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84)
                .addComponent(create_notice_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1173, Short.MAX_VALUE))
        );

        pic_outside_panel.add(skyblue_panel);
        skyblue_panel.setBounds(0, 0, 290, 1800);

        jPanel1.setBackground(new java.awt.Color(222, 243, 247));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Create Notice");

        notice_post_btn.setBackground(new java.awt.Color(0, 125, 234));
        notice_post_btn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        notice_post_btn.setForeground(new java.awt.Color(255, 255, 255));
        notice_post_btn.setText("Post");
        notice_post_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notice_post_btnActionPerformed(evt);
            }
        });

        notice_txt.setColumns(20);
        notice_txt.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        notice_txt.setRows(5);
        jScrollPane1.setViewportView(notice_txt);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 139, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(139, 139, 139))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(250, 250, 250)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(notice_post_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(287, 287, 287))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(notice_post_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );

        pic_outside_panel.add(jPanel1);
        jPanel1.setBounds(540, 210, 670, 360);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(blue_panel, javax.swing.GroupLayout.DEFAULT_SIZE, 1470, Short.MAX_VALUE)
            .addComponent(pic_outside_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(blue_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pic_outside_panel, javax.swing.GroupLayout.PREFERRED_SIZE, 820, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void history_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_history_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_history_btnActionPerformed

    private void create_notice_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_create_notice_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_create_notice_btnActionPerformed

    private void dashboard_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashboard_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dashboard_btnActionPerformed

    private void notice_post_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notice_post_btnActionPerformed
        // TODO add your handling code here:
        String text = notice_txt.getText().trim();

        NoticeController controller = new NoticeController();
        controller.saveNotice(text);
    }//GEN-LAST:event_notice_post_btnActionPerformed

    private void add_employee_btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_employee_btn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_add_employee_btn1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new NoticUi().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_employee_btn1;
    private javax.swing.JPanel blue_panel;
    private javax.swing.JLabel bms_text;
    private javax.swing.JButton create_notice_btn;
    private javax.swing.JButton dashboard_btn;
    private javax.swing.JButton history_btn;
    private javax.swing.JLabel horizon_text;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel logo;
    private javax.swing.JPanel logo_panel;
    private javax.swing.JButton notice_post_btn;
    private javax.swing.JTextArea notice_txt;
    private javax.swing.JPanel pic_outside_panel;
    private javax.swing.JPanel skyblue_panel;
    // End of variables declaration//GEN-END:variables
}
